# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
